-- Add new columns to users table
ALTER TABLE users 
ADD COLUMN phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN address VARCHAR(255) DEFAULT NULL,
ADD COLUMN city VARCHAR(100) DEFAULT NULL,
ADD COLUMN zip_code VARCHAR(20) DEFAULT NULL; 